In [32]:
import pandas as pd
import numpy as np
from scipy.stats import gmean
pd.set_option("display.max_columns", None)

In [33]:
df = pd.read_csv("bien_traits_summary.csv")
df.head(20)

/var/folders/h6/qd2kpqfj4_35f63hmcw_m0nc0000gn/T/ipykernel_4170/1996813199.py:1: DtypeWarning: Columns (2,4,8,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("bien_traits_summary.csv")

,scrubbed_species_binomial,trait_name,trait_value,unit,method,latitude,longitude,elevation_m,url_source,project_pi,project_pi_contact,access,id
0,Fraxinus americana,whole plant height,25.6032,m,NaN,43.810731,-71.470813,NaN,NaN,Greg Reams,NaN,public,26838000.0
1,Quercus rubra,whole plant height,21.336,m,NaN,43.637349,-72.083976,NaN,NaN,Greg Reams,NaN,public,26838033.0
2,Quercus rubra,whole plant height,23.4696,m,NaN,44.401370,-71.099594,NaN,NaN,Greg Reams,NaN,public,26838058.0
3,Quercus rubra,whole plant height,8.5344,m,NaN,44.064089,-71.960788,NaN,NaN,Greg Reams,NaN,public,26838073.0
4,Quercus rubra,whole plant height,11.8872,m,NaN,42.990632,-71.274879,NaN,NaN,Greg Reams,NaN,public,26838050.0
5,Fraxinus americana,whole plant height,22.86,m,NaN,43.883496,-71.743833,NaN,NaN,Greg Reams,NaN,public,26838064.0
6,Quercus rubra,whole plant height,24.384,m,NaN,43.169580,-71.947917,NaN,NaN,Greg Reams,NaN,public,26838077.0
7,Quercus rubra,whole plant height,21.9456,m,NaN,42.746245,-71.460145,NaN,NaN,Greg Reams,NaN,public,26838078.0
8,Fraxinus americana,whole plant height,20.1168,m,NaN,43.143692,-72.104246,NaN,NaN,Greg Reams,NaN,public,26838020.0
9,Fraxinus nigra,whole plant height,11.5824,m,NaN,44.354441,-71.530688,NaN,NaN,Greg Reams,NaN,public,26838024.0
10,Fraxinus americana,whole plant height,19.812,m,NaN,43.825012,-71.516822,NaN,NaN,Greg Reams,NaN,public,26838090.0
11,Picea mariana,whole plant height,12.4968,m,NaN,44.156087,-71.448355,NaN,NaN,Greg Reams,NaN,public,26838147.0
12,Quercus rubra,whole plant height,22.2504,m,NaN,42.988881,-71.022796,NaN,NaN,Greg Reams,NaN,public,26838121.0
13,Fraxinus americana,whole plant height,17.6784,m,NaN,43.514209,-71.373453,NaN,NaN,Greg Reams,NaN,public,26838104.0
14,Quercus rubra,whole plant height,12.192,m,NaN,43.014921,-71.518851,NaN,NaN,Greg Reams,NaN,public,26838154.0
15,Quercus rubra,whole plant height,24.6888,m,NaN,43.586071,-71.988897,NaN,NaN,Greg Reams,NaN,public,26838195.0
16,Fraxinus americana,whole plant height,13.1064,m,NaN,43.497891,-72.321147,NaN,NaN,Greg Reams,NaN,public,26838170.0
17,Quercus rubra,whole plant height,17.0688,m,NaN,43.219674,-71.393322,NaN,NaN,Greg Reams,NaN,public,26838159.0
18,Quercus rubra,whole plant height,20.4216,m,NaN,43.219674,-71.393322,NaN,NaN,Greg Reams,NaN,public,26838160.0
19,Quercus rubra,whole plant height,16.4592,m,NaN,43.519308,-71.536670,NaN,NaN,Greg Reams,NaN,public,26838196.0

In [35]:
unique_vals = {
    col: df[col].unique()
    for col in df.columns
}
unique_vals

{'scrubbed_species_binomial': array(['Fraxinus americana', 'Quercus rubra', 'Fraxinus nigra',
        'Picea mariana', 'Quercus alba', 'Liquidambar styraciflua',
        'Quercus phellos', 'Magnolia virginiana', 'Quercus bicolor',
        'Pseudotsuga menziesii', 'Picea engelmannii', 'Pinus taeda',
        'Ulmus americana', 'Fraxinus pennsylvanica', 'Picea glauca',
        'Populus deltoides', 'Juglans cinerea', 'Juglans nigra',
        'Fraxinus quadrangulata', 'Cercis canadensis', 'Cornus florida',
        'Thuja plicata', 'Picea sitchensis', 'Umbellularia californica',
        'Pinus albicaulis', 'Pinus lambertiana', 'Inga laurina',
        'Castanea dentata', 'Carya illinoinensis', 'Pinus radiata',
        'Quercus lobata', 'Quercus agrifolia', 'Quercus wislizeni',
        'Sequoiadendron giganteum', 'Melaleuca quinquenervia',
        'Malus fusca', 'Laguncularia racemosa', 'Trichilia hirta',
        'Senna siamea', 'Erythroxylum rotundifolium', 'Pimenta racemosa',
        'Cedrela odorata', 'Swietenia macrophylla', 'Fraxinus velutina',
        'Quercus engelmannii', 'Platanus racemosa', 'Eucalyptus globulus',
        'Juglans californica', 'Ricinus communis', 'Moringa oleifera',
        'Juglans hindsii', 'Casuarina equisetifolia',
        'Erythroxylum areolatum', 'Syzygium malaccense',
        'Erythroxylum rufum', 'Syzygium jambos', 'Psidium guajava',
        'Vicia sativa', 'Inga leiocalycina', 'Fagus sylvatica',
        'Sarracenia flava', 'Nageia nagi', 'Symphonia globulifera',
        'Pterocarpus macrocarpus', 'Pouteria glomerata',
        'Hevea brasiliensis', 'Jacaranda copaia',
        'Erythroxylum carthagenense', 'Erythroxylum daphnites',
        'Hamamelis virginiana', 'Dalbergia cultrata',
        'Erythroxylum macrophyllum', 'Bursera bipinnata',
        'Caryocar brasiliense', 'Erythroxylum citrifolium',
        'Eugenia uniflora', 'Erythroxylum confusum',
        'Dicorynia guianensis', 'Inga oerstediana',
        'Erythroxylum squamatum', 'Camellia japonica',
        'Crataegus laevigata', 'Carallia brachiata',
        'Erythroxylum orinocense', 'Prunus mahaleb',
        'Vaccinium bracteatum', 'Quercus glauca', 'Elaeocarpus petiolatus',
        'Erythroxylum mucronatum', 'Toxicodendron radicans',
        'Fraxinus griffithii', 'Erythroxylum anguifugum',
        'Dalbergia cochinchinensis', 'Pouteria campechiana',
        'Cereus jamacaru', 'Aquilaria malaccensis',
        'Erythroxylum havanense', 'Syzygium luehmannii',
        'Zanthoxylum nitidum', 'Corylus avellana',
        'Erythroxylum fimbriatum', 'Dalbergia oliveri', 'Mesua ferrea',
        'Erythroxylum panamense', 'Sextonia rubra', 'Ficus hispida',
        'Sambucus nigra', 'Erythroxylum gracilipes',
        'Casuarina cunninghamiana', 'Oemleria cerasiformis',
        'Dionaea muscipula', 'Darlingtonia californica', 'Quercus suber',
        'Carex rostrata', 'Phragmites australis', 'Sarracenia leucophylla',
        'Eucalyptus viminalis', 'Fraxinus angustifolia', 'Fraxinus ornus',
        'Prunus avium', 'Quercus ilex', 'Pyrus communis',
        'Casuarina glauca', 'Fraxinus excelsior', 'Laurus nobilis',
        'Salix caprea', 'Quercus mongolica', 'Trifolium pratense',
        'Castanea crenata', 'Flueggea virosa', 'Viburnum tinus',
        'Cornus controversa', 'Sarracenia minor', 'Lysimachia thyrsiflora',
        'Heteromeles arbutifolia', 'Euphorbia tirucalli', 'Ficus carica',
        'Ginkgo biloba', 'Morus alba', 'Nephelium lappaceum',
        'Helianthus annuus', 'Symplocos macrophylla', 'Coffea canephora',
        'Persea americana', 'Carnegiea gigantea',
        'Eriophorum angustifolium', 'Fraxinus gooddingii',
        'Epilobium ciliatum', 'Frangula alnus', 'Filipendula ulmaria',
        'Jacaranda mimosifolia', 'Castanopsis eyrei', 'Quercus variabilis',
        'Lagerstroemia speciosa', 'Eucalyptus fibrosa', 'Larix sibirica',
        'Erythrophleum ivorense', 'Eucalyptus melliodora',
        'Rhizophora apiculata', 'Delonix regia', 'Bruguiera gymnorhiza',
        'Jatropha curcas', 'Pterocarpus santalinus',
        'Castanopsis chinensis', 'Castanea mollissima', 'Castanea sativa',
        'Quercus gilva', 'Juglans regia', 'Pterocarya stenoptera',
        'Bertholletia excelsa', 'Sonneratia caseolaris', 'Punica granatum',
        'Sonneratia alba', 'Reevesia pubescens', 'Microcos paniculata',
        'Fremontodendron californicum', 'Xylocarpus granatum',
        'Angophora floribunda', 'Eucalyptus albens', 'Corymbia maculata',
        'Eucalyptus caleyi', 'Eucalyptus coolabah',
        'Eucalyptus cladocalyx', 'Eucalyptus cloeziana',
        'Eucalyptus camaldulensis', 'Eucalyptus microcorys',
        'Eucalyptus tenuipes', 'Eucalyptus regnans',
        'Eucalyptus pauciflora', 'Eucalyptus urophylla', 'Plantago major',
        'Fraxinus mandshurica', 'Osmanthus fragrans', 'Fraxinus chinensis',
        'Paulownia fortunei', 'Vernicia montana', 'Bruguiera cylindrica',
        'Ceriops tagal', 'Mitragyna speciosa', 'Citrus medica',
        'Mitragyna parvifolia', 'Dovyalis caffra', 'Aegle marmelos',
        'Salix purpurea', 'Comarum palustre', 'Aquilaria sinensis',
        'Castanospermum australe', 'Nyctanthes arbor-tristis',
        'Nicotiana glauca', 'Gleditsia sinensis', 'Liquidambar formosana',
        'Corylus chinensis', 'Lumnitzera littorea',
        'Cupressus sempervirens', 'Trapa natans', 'Cryptomeria japonica',
        'Sparganium erectum', 'Eucalyptus erythrocorys',
        'Ceriops decandra', 'Lythrum hyssopifolia',
        'Aesculus hippocastanum', 'Mentha aquatica', 'Sparganium emersum',
        'Hordeum marinum', 'Lithocarpus litseifolius',
        'Quercus aquifolioides', 'Quercus cerris', 'Quercus robur',
        'Quercus petraea', 'Litsea cubeba', 'Ormosia semicastrata',
        'Khaya senegalensis', 'Melia azedarach', 'Eleocharis quinqueflora',
        'Ficus benjamina', 'Eleusine indica', 'Juncus effusus',
        'Corymbia calophylla', 'Eucalyptus marginata',
        'Eucalyptus shirleyi', 'Epilobium hirsutum', 'Paulownia tomentosa',
        'Mimosa bimucronata', 'Pinus tabuliformis', 'Corylus americana',
        'Bruguiera parviflora', 'Bruguiera sexangula',
        'Bruguiera hainesii', 'Populus euphratica',
        'Vaccinium vitis-idaea', 'Bretschneidera sinensis',
        'Eriophorum vaginatum', 'Tabernaemontana elegans',
        'Handroanthus impetiginosus', 'Lumnitzera racemosa',
        'Juniperus phoenicea', 'Terminalia arjuna', 'Geum rivale',
        'Impatiens noli-tangere', 'Hottonia palustris',
        'Spergularia marina', 'Lobelia dortmanna', 'Mentha suaveolens',
        'Mentha longifolia', 'Nymphoides peltata', 'Myrica gale',
        'Schoenus nigricans', 'Samolus valerandi', 'Lupinus albus',
        'Lupinus luteus', 'Phaseolus vulgaris', 'Staphylea pinnata',
        'Typha latifolia', 'Portulaca oleracea', 'Veronica scutellata',
        'Salix viminalis', 'Fraxinus anomala', 'Salvia officinalis',
        'Schoenoplectus tabernaemontani', 'Viola palustris',
        'Scirpus sylvaticus', 'Schoenoplectus triqueter',
        'Veronica serpyllifolia', 'Vicia tenuifolia', 'Syringa vulgaris',
        'Carex echinata', 'Carex distans', 'Carex acutiformis',
        'Carex elata', 'Carex punctata', 'Carex nigra', 'Carex extensa',
        'Spergularia bocconei', 'Carex riparia', 'Corrigiola litoralis',
        'Erythroxylum gonoclados', 'Cyperus rotundus', 'Cyperus fuscus',
        'Trifolium subterraneum', 'Erythroxylum williamsii',
        'Gossypium thurberi', 'Liriodendron chinense', 'Nelumbo lutea',
        'Ficus religiosa', 'Prunus salicina', 'Lupinus angustifolius',
        'Pistacia vera', 'Pistacia atlantica', 'Juniperus oxycedrus',
        'Cornus kousa', 'Corylus heterophylla', 'Erythroxylum ulei',
        'Pyrus betulifolia', 'Tetraclinis articulata', 'Diospyros lotus',
        'Vaccinium floribundum', 'Vaccinium macrocarpon',
        'Erythroxylum bequaertii', 'Erythroxylum haughtii',
        'Eucommia ulmoides', 'Erythroxylum subrotundum',
        'Manihot glaziovii', 'Ceratonia siliqua', 'Lathyrus linifolius',
        'Phaseolus lunatus', 'Quercus dentata', 'Silybum marianum',
        'Quercus tomentella', 'Isoetes engelmannii', 'Iris virginica',
        'Pterocarya macroptera', 'Phaseolus coccineus',
        'Adansonia grandidieri', 'Theobroma grandiflorum',
        'Gossypium aridum', 'Gossypium davidsonii',
        'Gossypium gossypioides', 'Gossypium harknessii',
        'Trichilia minutiflora', 'Ficus microcarpa', 'Musa balbisiana',
        'Musa textilis', 'Abeliophyllum distichum', 'Fraxinus cuspidata',
        'Fraxinus greggii', 'Sanguinaria canadensis', 'Vanilla planifolia',
        'Aegilops bicornis', 'Leersia oryzoides', 'Leersia perrieri',
        'Oryza brachyantha', 'Oryza australiensis', 'Oryza barthii',
        'Oryza glaberrima', 'Oryza longistaminata', 'Oryza rufipogon',
        'Oryza officinalis', 'Oryza punctata', 'Paspalum vaginatum',
        'Pharus latifolius', 'Aegilops sharonensis', 'Zea luxurians',
        'Hordeum pubiflorum', 'Triticum monococcum', 'Posidonia oceanica',
        'Zizania palustris', 'Telopea speciosissima',
        'Macadamia integrifolia', 'Cardiospermum halicacabum',
        'Quillaja saponaria', 'Cinchona calisaya', 'Gardenia jasminoides',
        'Citrus maxima', 'Zanthoxylum armatum', 'Dipteronia dyeriana',
        'Santalum album', 'Lycium ruthenicum', 'Capsicum annuum',
        'Sarracenia psittacina', 'Solanum bulbocastanum',
        'Nicotiana otophora', 'Solanum pinnatisectum',
        'Solanum peruvianum', 'Solanum pimpinellifolium',
        'Ulmus parvifolia', 'Tamarix chinensis', 'Camellia crapnelliana',
        'Phyllospadix torreyi', 'Zostera marina', 'Sophora flavescens',
        'Calotropis procera', 'Voacanga thouarsii', 'Ilex paraguariensis',
        'Colocasia esculenta', 'Elaeis guineensis', 'Syagrus oleracea',
        'Helianthus anomalus', 'Corylus colurna', 'Cyperus iria',
        'Tillandsia fasciculata', 'Bursera cuneata', 'Bursera palmeri',
        'Buxus sempervirens', 'Pachycereus pringlei',
        'Stenocereus thurberi', 'Lobelia cardinalis', 'Ipomoea aquatica',
        'Ipomoea trifida', 'Centella asiatica', 'Oenanthe javanica',
        'Cyperus esculentus', 'Schoenoplectus lacustris',
        'Rumohra adiantiformis', 'Rhododendron ferrugineum',
        'Ilex aquifolium', 'Lathyrus aphaca', 'Primula scotica',
        'Prunus fruticosa', 'Caragana arborescens', 'Chamaerops humilis',
        'Chimonanthus praecox', 'Camellia oleifera', 'Ziziphus jujuba',
        'Protea cynaroides', 'Cicer reticulatum', 'Ensete glaucum',
        'Utricularia gibba', 'Medicago truncatula', 'Fraxinus floribunda',
        'Metroxylon sagu', 'Fraxinus platypoda', 'Brasenia schreberi',
        'Salix exigua', 'Diplocyclos schliebenii', 'Ensete ventricosum',
        'Calochortus purpureus', 'Lupinus cosentinii', 'Ipomoea triloba',
        'Crataegus pinnatifida', 'Gastrodia elata', 'Dracaena cambodiana',
        'Vigna angularis', 'Hakea prostrata', 'Ochetophila trinervis',
        'Euryodendron excelsum', 'Erythropalum scandens',
        'Gnetum montanum', 'Syzygium grande', 'Lindera aggregata',
        'Eucalyptus pumila', 'Eucalyptus curtisii',
        'Eucalyptus lansdowneana', 'Eucalyptus decipiens',
        'Eucalyptus dawsonii', 'Eucalyptus guilfoylei',
        'Eucalyptus polybractea', 'Fraxinus xanthoxyloides',
        'Juniperus thurifera', 'Prunus mume', 'Zanthoxylum bungeanum',
        'Handroanthus guayacan', 'Dracaena draco', 'Tamarix gallica',
        'Erythroxylum kapplerianum', 'Haberlea rhodopensis',
        'Melastoma sanguineum'], dtype=object),
 'trait_name': array(['whole plant height', 'whole plant growth form', 'leaf area',
        'stem wood density', 'seed mass', 'whole plant sexual system',
        'flower pollination syndrome', 'fruit type'], dtype=object),
 'trait_value': array([25.6032, 21.336, 23.4696, ..., '0.578', '2.82', '9630'],
       dtype=object),
 'unit': array(['m', nan, 'mm2', 'g.cm-3', 'mg'], dtype=object),
 'method': array([nan, 'Measured as in Cornelissen et al. (2003)',
        'measurement in greenhouse',
        'We measured leaf area from scanned leaves and petioles using imagej. For species with compound leaves, we calculated leaf area as the mean leaflet area per leaf including petioles.',
        'actual measurement',
        'Average leaf size, measured from shade-grown whole leaves or leaflets',
        'maximum height calculated from species-specific height-diameter relationships',
        'Wood samples were collected from woody species present within the plot at >1% cover in shrub, subcanopy or canopy strata, which had trunks robust enough to core. A 100-mm wood sample from each of two individuals per species was extracted using a 5.15-mm-diameter, triple-threaded increment borer (HaglÃ¶f Sweden). Samples were extracted from the base of the main trunk, 10 cm above the leaf litter level, and air-dried at 20Â\x9645 Â°C. Samples were then rehydrated to saturation in deionized water and 10-mm sections of mature heartwood were cut flush with a razor, using visual inspection of vessel occlusion as an indicator of maturity. Sections were measured (x, y and z dimensions) to the nearest 0.01 mm with callipers (Mitutoyo America Corporation, Aurora, IL, USA) to calculate wet volume, then oven-dried at 80 Â°C for 48 h and weighed using a microbalance (Mettler Toledo, Greifensee, Switzerland). Wood density was then calculated as the ratio of oven dry mass to wet volume.',
        'oven dry mass/fresh volume',
        'The leaf size was measured using the software winfolia version 2002 (RÃ©gent, Quebec, Canada).',
        'Tree height (h) was measured using an Impulse LR laser (Laser Technology, Inc., Norristown, PA).',
        'Estimated or measured leaf area (mean value)', 'max height',
        'The leaf samples were scanned flat to measure their area using WinFOLIA software (Regent Instruments, Canada) and then oven-dried at 70 Â°C for 3 days and weighed to determine their dry mass.',
        'Wood density of mature individuals was determined from published sources (Aiba & Nakashizuka 2009). When no published data were available for wood density, we measured it using one wood core sample from each of three individuals per species in November 2011, following the method of Aiba&Nakashizuka (2009).',
        'Extracted from a database', 'X-ray densitometry',
        'data compilation', 'Maximum height',
        'Heights, measured for 156 of these trees using a Vertex hypsometer, were used to select site indices for each plot, and these were used to estimate height of all remaining trees using local allometric equations (Scrinzi, Galvagni & Marzullo 2010).',
        'taken at 22 years old', 'average of seed mass measurements',
        'actual measurement (following LEDA data standards)',
        'air-dried weight of mature, undamaged seeds without attachments - mean value',
        'oven dry mass/fresh volume;data compilation',
        'laboratory/greenhouse/garden experiment', 'field experiment',
        'Species with multiple growth form classifications were assigned the growth form classification agreed upon by the majority (>2/3) of sources. Species with ambiguous or otherwise not interpretable growth form assignments were excluded from the final dataset but are made available with the original data.',
        'actual measurement (following LEDA data standards) - maximum height',
        'Five young fully expanded healthy leaves collected from outer canopy, scanned using LiCor or LI-3100 Area Meter or CanoScan LiDE35.',
        'data compilation; average of 1000 seeds',
        'Area of dry blade calculated on photographies',
        'Leaf images were used to obtain leaf area and perimeter with ImageJ (Schneider et al., 2012).',
        'These measurements are taken from of a larger dataset assembled by Cornwell. Cornwell, W.K., Westoby, M., Falster, D.S. et al. (2014) Functional distinctiveness of major plant lineages. Journal of Ecology, 102, 345Â\x96356.',
        'mass of individual seed',
        'distance from  soil surface to the highest node of the main shoot',
        'one-sided projected surface area',
        'WinDIAS Image Analysis System, Delta-T Devices, Cambridge, UK',
        'leaf area x number of leaves', 'taken at 10 years old',
        'Area of leaf blade (excluding petiole)',
        'Measured at 15 years old', 'Measured at 20 years old',
        'Measured at 25 years old', 'Measured at 30 years old',
        'Measured at 35 years old', 'Measured at 32 years old',
        'Measured at 40 years old', 'Measured at 45 years old',
        'Measured at 50 years old', 'Measured at 55 years old',
        'Measured at 60 years old', 'Measured at 62 years old',
        'Measured at 70 years old', 'Measured at 75 years old',
        'The seedlings were dried at 60 Â°C for at least 4 days and weighed on a balance readable to 0.01 mg. All 20 seed embryos were weighed together and the total biomass was divided by 20 to obtain the mean weight.',
        'Mean seed dry mass, measured with a digital scale after drying at 60 C, where seed is defined to include the endosperm and embryo only.',
        'Wood samples of each tree part (top and bottom of commercial bole, large branches, and small branches) were taken from freshly cut wood. When the stem was cut into more than two sections, a sample was collected from the bottom or top of every section (with the top of one section corresponding to the bottom of the next). Wood samples were cut as disks of constant thickness in small branches and as wedges of constant thickness, extending from the centre to the bark, in large branches and stems (minimum 100 g). Fresh mass was measured immediately with a hanging scale with 1-g precision.',
        'Wood density was measured at a resolution of 25<U+2009>Âµm by X-ray densitometry that corresponds to density at 8% moisture content.'],
       dtype=object),
 'latitude': array([ 43.810731,  43.637349,  44.40137 , ..., -12.4808  , -12.5483  ,
        -12.6257  ]),
 'longitude': array([-71.470813, -72.083976, -71.099594, ..., -69.3853  , -68.7717  ,
        -68.7535  ]),
 'elevation_m': array([  nan,  330.,  500.,  366.,  130.,  635.,  118.,  362.,  677.,
         653.,  750.,   25.,  670.,  175., 1300.,  492.,  270.,  600.,
         700.,  610.,  915., 1550.,  305.,  850.,  251.,  340., 1580.,
          44.,  313.]),
 'url_source': array([nan, 'http://datadryad.org/resource/doi:10.5061/dryad.512p5',
        'http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf112',
        'http://datadryad.org/resource/doi:10.5061/dryad.rr4pm',
        'doi:10.1007/s00442-008-1131-x',
        'http://datadryad.org/resource/doi:10.5061/dryad.j25t0',
        'doi:10.1890/09-1672.1', 'doi: 10.1093/aob/mcn103',
        'http://datadryad.org/resource/doi:10.5061/dryad.72h45',
        'http://ucjeps.berkeley.edu/EFT.html',
        'http://datadryad.org/resource/doi:10.5061/dryad.1284',
        'http://datadryad.org/resource/doi:10.5061/dryad.6nc8c',
        'http://datadryad.org/resource/doi:10.5061/dryad.b5tr9',
        'http://datadryad.org/resource/doi:10.5061/dryad.d87v7',
        'http://datadryad.org/resource/doi:10.5061/dryad.dr275.2',
        'http://datadryad.org/resource/doi:10.5061/dryad.k67j5',
        'http://datadryad.org/resource/doi:10.5061/dryad.rj480',
        'http://datadryad.org/resource/doi:10.5061/dryad.5q33h',
        'http://datadryad.org/resource/doi:10.5061/dryad.v240b',
        'http://datadryad.org/resource/doi:10.5061/dryad.8kb37',
        'https://hub.hku.hk/bitstream/10722/44716/1/67814.pdf?accept=1',
        'https://pdfs.semanticscholar.org/b407/4eba9d8ed375b0c6c502501f21f2913d1777.pdf',
        'http://datadryad.org/resource/doi:10.5061/dryad.hf5rh',
        'http://datadryad.org/resource/doi:10.5061/dryad.6rd6f',

In [36]:
traits = df["trait_name"].unique()

trait_dfs = {
    trait: df[df["trait_name"] == trait].copy()
    for trait in traits
}
traits

array(['whole plant height', 'whole plant growth form', 'leaf area',
       'stem wood density', 'seed mass', 'whole plant sexual system',
       'flower pollination syndrome', 'fruit type'], dtype=object)

In [37]:
trait_dfs["whole plant height"]

,scrubbed_species_binomial,trait_name,trait_value,unit,method,latitude,longitude,elevation_m,url_source,project_pi,project_pi_contact,access,id
0,Fraxinus americana,whole plant height,25.6032,m,NaN,43.810731,-71.470813,NaN,NaN,Greg Reams,NaN,public,26838000.0
1,Quercus rubra,whole plant height,21.336,m,NaN,43.637349,-72.083976,NaN,NaN,Greg Reams,NaN,public,26838033.0
2,Quercus rubra,whole plant height,23.4696,m,NaN,44.401370,-71.099594,NaN,NaN,Greg Reams,NaN,public,26838058.0
3,Quercus rubra,whole plant height,8.5344,m,NaN,44.064089,-71.960788,NaN,NaN,Greg Reams,NaN,public,26838073.0
4,Quercus rubra,whole plant height,11.8872,m,NaN,42.990632,-71.274879,NaN,NaN,Greg Reams,NaN,public,26838050.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3068126,Picea mariana,whole plant height,12.192,m,NaN,NaN,NaN,NaN,NaN,Greg Reams,NaN,public,2024156.0
3068127,Quercus rubra,whole plant height,13.716,m,NaN,NaN,NaN,NaN,NaN,Greg Reams,NaN,public,2024184.0
3068128,Quercus rubra,whole plant height,17.0688,m,NaN,NaN,NaN,NaN,NaN,Greg Reams,NaN,public,2024189.0
3068129,Quercus rubra,whole plant height,21.336,m,NaN,NaN,NaN,NaN,NaN,Greg Reams,NaN,public,2024193.0
3068130,Fraxinus nigra,whole plant height,15.24,m,NaN,NaN,NaN,NaN,NaN,Greg Reams,NaN,public,2024197.0

In [38]:
# plant height df
df["trait_value"].map(type).value_counts()

trait_value
<class 'float'>    2883584
<class 'str'>       184547
Name: count, dtype: int64

In [49]:
# plant height df
h = trait_dfs["whole plant height"].copy()
h["scrubbed_species_binomial"] = h["scrubbed_species_binomial"].astype(str).str.strip().str.lower()
h["plant_height_m"] = pd.to_numeric(h["trait_value"], errors="coerce")
h = h.dropna(subset=["scrubbed_species_binomial", "plant_height_m"])

height_summary = h.groupby("scrubbed_species_binomial").agg(
    plant_height_m_mean=("plant_height_m", "mean"),
    plant_height_m_min=("plant_height_m", "min"),
    plant_height_m_max=("plant_height_m", "max"),
    unit=("unit", lambda x: "; ".join(x.dropna().unique())),
    project_pi=("project_pi", lambda x: "; ".join(x.dropna().unique())),
)

height_summary = height_summary.reset_index()

height_summary

,scrubbed_species_binomial,plant_height_m_mean,plant_height_m_min,plant_height_m_max,unit,project_pi
0,aesculus hippocastanum,23.800000,20.0000,39.0000,m,Michael Kleyer; Price CA
1,buxus sempervirens,2.250000,0.3000,5.0000,m,Michael Kleyer; Price CA
2,camellia japonica,11.000000,11.0000,11.0000,m,Price CA
3,capsicum annuum,0.126828,0.0092,0.6173,m,Milla R
4,caragana arborescens,3.500000,2.0000,6.0000,m,Michael Kleyer
...,...,...,...,...,...,...
199,vicia sativa,0.696687,0.0500,1.3870,m,Loughnan D; Michael Kleyer; DostÃ¡l P; Marx HE
200,vicia tenuifolia,0.655000,0.2700,1.5000,m,Michael Kleyer
201,viola palustris,0.085000,0.0500,0.1200,m,Michael Kleyer
202,ziziphus jujuba,12.954000,11.8872,14.0208,m,
203,zostera marina,2.500000,2.5000,2.5000,m,Marx HE

In [40]:
height_summary.to_csv("bien_summary_plant_height.csv", index=False)

In [50]:
# leaf area dataframe
la = trait_dfs["leaf area"].copy()
la["scrubbed_species_binomial"] = la["scrubbed_species_binomial"].astype(str).str.strip().str.lower()
la["leaf_area_mm2"] = pd.to_numeric(la["trait_value"], errors="coerce")

la = la.dropna(subset=["scrubbed_species_binomial", "leaf_area_mm2"])

leaf_area_summary = la.groupby("scrubbed_species_binomial").agg(
    leaf_area_m2_mean=("leaf_area_mm2", "mean"),
    leaf_area_m2_min=("leaf_area_mm2", "min"),
    leaf_area_m2_max=("leaf_area_mm2", "max"),
    unit=("unit", lambda x: "; ".join(x.dropna().unique())),
    project_pi=("project_pi", lambda x: "; ".join(x.dropna().unique())),
)

leaf_area_summary = leaf_area_summary.reset_index()

leaf_area_summary

,scrubbed_species_binomial,leaf_area_m2_mean,leaf_area_m2_min,leaf_area_m2_max,unit,project_pi
0,aesculus hippocastanum,6528.700000,6331.60,6725.8,mm2,K. Thompson; Price CA
1,buxus sempervirens,141.960000,108.10,180.3,mm2,Price CA; K. Thompson
2,capsicum annuum,732.809091,165.60,2650.1,mm2,Milla R
3,caragana arborescens,1059.500000,1059.50,1059.5,mm2,D.K. Kunzmann
4,carex acutiformis,7035.000000,7035.00,7035.0,mm2,K. Thompson
...,...,...,...,...,...,...
131,veronica serpyllifolia,188.000000,188.00,188.0,mm2,K. Thompson; Marx HE
132,viburnum tinus,1799.540000,1435.80,2313.0,mm2,K. Thompson; de la Riva EG; Price CA
133,vicia sativa,664.981420,186.25,1393.0,mm2,D.K. Kunzmann; K. Thompson; Marx HE
134,vicia tenuifolia,1904.606667,1059.00,2413.0,mm2,K. Thompson; D.K. Kunzmann
135,viola palustris,1812.916667,527.75,3288.0,mm2,K. Thompson; KrÃÂ¼ger

In [42]:
leaf_area_summary.to_csv("bien_summary_leaf_area.csv", index=False)

In [52]:
# stem wood density dataframe
wd = trait_dfs["stem wood density"].copy()
wd["scrubbed_species_binomial"] = wd["scrubbed_species_binomial"].astype(str).str.strip().str.lower()
wd["stem_wood_density_g_cm3"] = pd.to_numeric(wd["trait_value"], errors="coerce")

wd = wd.dropna(subset=["scrubbed_species_binomial", "stem_wood_density_g_cm3"])

stem_wood_density_summary = wd.groupby("scrubbed_species_binomial").agg(
    stem_wood_density_g_cm3_mean=("stem_wood_density_g_cm3", "mean"),
    stem_wood_density_g_cm3_min=("stem_wood_density_g_cm3", "min"),
    stem_wood_density_g_cm3_max=("stem_wood_density_g_cm3", "max"),
    unit=("unit", lambda x: "; ".join(x.dropna().unique())),
    project_pi=("project_pi", lambda x: "; ".join(x.dropna().unique())),
)

stem_wood_density_summary = stem_wood_density_summary.reset_index()

stem_wood_density_summary

,scrubbed_species_binomial,stem_wood_density_g_cm3_mean,stem_wood_density_g_cm3_min,stem_wood_density_g_cm3_max,unit,project_pi
0,aegle marmelos,0.825614,0.771000,0.880,g.cm-3,"Zanne, A.E., Lopez-Gonzalez, G., Coomes, D.A...."
1,aesculus hippocastanum,0.500000,0.500000,0.500,g.cm-3,"Zanne, A.E., Lopez-Gonzalez, G., Coomes, D.A...."
2,angophora floribunda,0.725227,0.660000,0.758,g.cm-3,"Zanne, A.E., Lopez-Gonzalez, G., Coomes, D.A...."
3,aquilaria malaccensis,0.320000,0.320000,0.320,g.cm-3,"Zanne, A.E., Lopez-Gonzalez, G., Coomes, D.A...."
4,aquilaria sinensis,0.366079,0.344000,0.380,g.cm-3,"Zanne, A.E., Lopez-Gonzalez, G., Coomes, D.A...."
...,...,...,...,...,...,...
197,umbellularia californica,0.511667,0.510000,0.515,g.cm-3,"D.D. Ackerly; Zanne, A.E., Lopez-Gonzalez, G...."
198,vernicia montana,0.318497,0.315987,0.321,g.cm-3,"Zanne, A.E., Lopez-Gonzalez, G., Coomes, D.A...."
199,viburnum tinus,0.465000,0.460000,0.470,g.cm-3,de la Riva EG
200,xylocarpus granatum,0.591206,0.525000,0.663,g.cm-3,"Zanne, A.E., Lopez-Gonzalez, G., Coomes, D.A...."
201,ziziphus jujuba,0.800000,0.680000,0.920,g.cm-3,"Lopez-Gonzalez G; Zanne, A.E., Lopez-Gonzalez..."

In [55]:
stem_wood_density_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   scrubbed_species_binomial     202 non-null    object
 1   stem_wood_density_g_cm3_mean  202 non-null    float64
 2   stem_wood_density_g_cm3_min   202 non-null    float64
 3   stem_wood_density_g_cm3_max   202 non-null    float64
 4   unit                          202 non-null    object
 5   project_pi                    202 non-null    object
dtypes: float64(3), object(3)
memory usage: 9.6+ KB

In [44]:
stem_wood_density_summary.to_csv("bien_summary_stem_wood_density.csv", index=False)

In [54]:
# whole plant sexual system dataset
ss = trait_dfs["whole plant sexual system"].copy()
ss["scrubbed_species_binomial"] = ss["scrubbed_species_binomial"].astype(str).str.strip().str.lower()

def most_frequent(x):
    vc = x.value_counts()
    return vc.index[0] if not vc.empty else pd.NA

sexual_system_summary = ss.groupby("scrubbed_species_binomial").agg(
    sexual_system=("trait_value", most_frequent),
    project_pi=("project_pi", lambda x: "; ".join(x.dropna().astype(str).unique())),
)

sexual_system_summary = sexual_system_summary.reset_index()

sexual_system_summary

   scrubbed_species_binomial  sexual_system project_pi
0       bruguiera gymnorhiza  Hermaphrodite  Bezeng BS
1         calotropis procera  Hermaphrodite  Bezeng BS
2   casuarina cunninghamiana  Hermaphrodite  Bezeng BS
3    casuarina equisetifolia  Hermaphrodite  Bezeng BS
4            cereus jamacaru  Hermaphrodite  Bezeng BS
5              ceriops tagal  Hermaphrodite  Bezeng BS
6              delonix regia  Hermaphrodite  Bezeng BS
7            dovyalis caffra      Dioecious  Bezeng BS
8         ensete ventricosum  Hermaphrodite  Bezeng BS
9   eucalyptus camaldulensis  Hermaphrodite  Bezeng BS
10       eucalyptus globulus  Hermaphrodite  Bezeng BS
11          eugenia uniflora  Hermaphrodite  Bezeng BS
12       euphorbia tirucalli  Hermaphrodite  Bezeng BS
13              ficus carica      Dioecious  Bezeng BS
14           flueggea virosa      Dioecious  Bezeng BS
15        fraxinus americana      Dioecious  Bezeng BS
16     fraxinus angustifolia      Dioecious  Bezeng BS
17    fraxinus pennsylvanica      Dioecious  Bezeng BS
18     jacaranda mimosifolia  Hermaphrodite  Bezeng BS
19           jatropha curcas  Hermaphrodite  Bezeng BS
20   liquidambar styraciflua  Hermaphrodite  Bezeng BS
21       lumnitzera racemosa  Hermaphrodite  Bezeng BS
22           melia azedarach  Hermaphrodite  Bezeng BS
23          moringa oleifera  Hermaphrodite  Bezeng BS
24                morus alba  Hermaphrodite  Bezeng BS
25          nicotiana glauca  Hermaphrodite  Bezeng BS
26          persea americana  Hermaphrodite  Bezeng BS
27             pinus radiata  Hermaphrodite  Bezeng BS
28               pinus taeda  Hermaphrodite  Bezeng BS
29         populus deltoides      Dioecious  Bezeng BS
30           psidium guajava  Hermaphrodite  Bezeng BS
31           punica granatum  Hermaphrodite  Bezeng BS
32             quercus robur  Hermaphrodite  Bezeng BS
33          ricinus communis  Hermaphrodite  Bezeng BS
34            sambucus nigra  Hermaphrodite  Bezeng BS
35           sonneratia alba  Hermaphrodite  Bezeng BS
36           syzygium jambos  Hermaphrodite  Bezeng BS
37   tabernaemontana elegans  Hermaphrodite  Bezeng BS
38         tamarix chinensis  Hermaphrodite  Bezeng BS
39           tamarix gallica  Hermaphrodite  Bezeng BS
40        voacanga thouarsii  Hermaphrodite  Bezeng BS

In [46]:
sexual_system_summary.to_csv("bien_summary_sexual_system.csv", index=False)