In [25]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

In [26]:
df = pd.read_csv("GIFT-db_traits.csv")
df.head(20)

,work_ID,work_species,work_author,trait_value_Plant_height_min,trait_value_Plant_height_max,trait_value_Plant_height_mean,trait_value_Lifecycle_1,trait_value_Lifespan_1,trait_value_Dispersal_syndrome_1,trait_value_Life_form_2,trait_value_Deciduousness_1,trait_value_Self_fertilization_1,trait_value_Seed_length_max,trait_value_Seed_length_mean,trait_value_Seed_width_mean,trait_value_Fruit_length_min,trait_value_Fruit_width_mean,trait_value_Fruit_height_mean,trait_value_Seed_volume_mean,trait_value_Monocarpy,trait_value_Seed_length_min,trait_value_Dispersal_syndrome_2,trait_value_Reproduction_sexual_1,trait_value_Reproduction_asexual_1,trait_value_Reproduction_asexual_2,trait_value_Pollination_syndrome_1,trait_value_Pollination_syndrome_2,trait_value_Pollination_syndrome_3,trait_value_SSD_mean,trait_value_Leaf_size_mean,trait_value_Chromosome_number,trait_value_Ploidy_level,agreement_Lifecycle_1,agreement_Dispersal_syndrome_1,agreement_Life_form_2,agreement_Deciduousness_1,agreement_Self_fertilization_1,agreement_Monocarpy,agreement_Dispersal_syndrome_2,agreement_Reproduction_sexual_1,agreement_Reproduction_asexual_1,agreement_Reproduction_asexual_2,agreement_Pollination_syndrome_1,agreement_Pollination_syndrome_2,agreement_Pollination_syndrome_3,agreement_Chromosome_number,agreement_Ploidy_level,cv_Plant_height_min,cv_Plant_height_max,cv_Plant_height_mean,cv_Lifespan_1,cv_Seed_length_max,cv_Seed_length_mean,cv_Seed_width_mean,cv_Fruit_length_min,cv_Fruit_width_mean,cv_Fruit_height_mean,cv_Seed_volume_mean,cv_Seed_length_min,cv_SSD_mean,cv_Leaf_size_mean,n_Plant_height_min,n_Plant_height_max,n_Plant_height_mean,n_Lifecycle_1,n_Lifespan_1,n_Dispersal_syndrome_1,n_Life_form_2,n_Deciduousness_1,n_Self_fertilization_1,n_Seed_length_max,n_Seed_length_mean,n_Seed_width_mean,n_Fruit_length_min,n_Fruit_width_mean,n_Fruit_height_mean,n_Seed_volume_mean,n_Monocarpy,n_Seed_length_min,n_Dispersal_syndrome_2,n_Reproduction_sexual_1,n_Reproduction_asexual_1,n_Reproduction_asexual_2,n_Pollination_syndrome_1,n_Pollination_syndrome_2,n_Pollination_syndrome_3,n_SSD_mean,n_Leaf_size_mean,n_Chromosome_number,n_Ploidy_level,references_Plant_height_min,references_Plant_height_max,references_Plant_height_mean,references_Lifecycle_1,references_Lifespan_1,references_Dispersal_syndrome_1,references_Life_form_2,references_Deciduousness_1,references_Self_fertilization_1,references_Seed_length_max,references_Seed_length_mean,references_Seed_width_mean,references_Fruit_length_min,references_Fruit_width_mean,references_Fruit_height_mean,references_Seed_volume_mean,references_Monocarpy,references_Seed_length_min,references_Dispersal_syndrome_2,references_Reproduction_sexual_1,references_Reproduction_asexual_1,references_Reproduction_asexual_2,references_Pollination_syndrome_1,references_Pollination_syndrome_2,references_Pollination_syndrome_3,references_SSD_mean,references_Leaf_size_mean,references_Chromosome_number,references_Ploidy_level
0,1002,Aesculus hippocastanum,L.,15.00,30.0,20.166667,perennial,NaN,NaN,phanerophyte,deciduous,absent,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,absent,NaN,biotic,insect,bee,510.0,65.28700,NaN,NaN,1.0,NaN,1.000,1.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.315,0.161,0.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5.0,3.0,7.0,NaN,NaN,7.0,3.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,1.0,1.0,1.0,1.0,NaN,NaN,"10302,10315,10353","10302,10315,10328,10353,10651","10191,10328,10353","10129,10132,10233,10243,10315,10353,10651",NaN,NaN,"10132,10215,10227,10290,10302,10315,10328","10243,10328,10353",10313,NaN,NaN,10328.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10315,NaN,"10313,10315",10313,10315,10191,10191.0,NaN,NaN
1,2776,Aquilaria yunnanensis,S.C.Huang,3.00,8.0,5.750000,perennial,NaN,NaN,NaN,evergreen,NaN,NaN,NaN,NaN,2.5,1.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,4.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10353,10353,"10199,10353","10199,10243,10353,10203",NaN,NaN,NaN,10199,NaN,NaN,NaN,NaN,10353,10353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5836,Bretschneidera sinensis,Hemsl.,10.00,20.0,15.000000,perennial,NaN,NaN,phanerophyte,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,6.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10353,10353,10353,"10243,10353,10190,10233,10248,10280",NaN,NaN,+10193,NaN,NaN,NaN,NaN,NaN,10353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5968,Bruguiera gymnorhiza,(L.) Lam.,7.00,36.0,15.000000,perennial,NaN,hydrochorous,NaN,evergreen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hydrochorous,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,0.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.250,1.042,0.471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,2.0,18.0,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10018,10111","10111,10318,10320","10199,10233","10018,10111,10199,10243,10353,10190,80,10233,2...",NaN,"10255,10599",NaN,10199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10599,10349",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5971,Bruguiera parviflora,(Roxb.) Wight & Arn. ex Griff.,1.00,24.0,24.000000,perennial,NaN,hydrochorous,NaN,evergreen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,11.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10018,"10018,10318",10199,"10018,10129,10199,10190,80,10233,10248,10280,2...",NaN,10255,NaN,10199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5972,Bruguiera sexangula,(Lour.) Poir.,1.00,33.0,12.250000,perennial,NaN,hydrochorous,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,biotic,insect,insect,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,0.862,0.895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,10.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10353,"10318,10353","10199,10353","10129,10199,10243,10353,10190,10233,10248,1028...",NaN,10255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10199,10199,10199,NaN,NaN,NaN,NaN
6,6386,Buxus sempervirens,L.,1.00,8.0,3.000000,perennial,NaN,NaN,phanerophyte,evergreen,absent,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,monoecious,absent,NaN,biotic,insect,insect,910.0,1.38750,NaN,NaN,1.0,NaN,0.833,1.0,1.0,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.000,0.353,0.471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5.0,2.0,7.0,NaN,NaN,9.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,1.0,NaN,2.0,2.0,1.0,1.0,1.0,NaN,NaN,"10302,10315,10651","10247,10302,10315,10328,10651","10191,10328","10016,10114,10129,10233,10315,10334,10651",NaN,NaN,"10114,10215,10247,10191,10290,10315,10328,10302",10313,10247,10328,10328.0,NaN,NaN,NaN,NaN,NaN,NaN,10328,NaN,"10247,10328",10315,NaN,"10247,10315","10247,10315",10315,10191,10191.0,NaN,NaN
7,7177,Calotropis procera,(Aiton) W.T.Aiton,1.00,5.0,4.000000,perennial,NaN,anemochorous,phanerophyte,NaN,absent,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,biotic,insect,insect,NaN,NaN,NaN,NaN,1.0,1.0,0.714,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,0.000,0.306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5.0,1.0,19.0,NaN,1.0,7.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,"10018,10111,10319,10342","10018,10111,10246,10319,10342",10199,"10018,10020,10060,10071,10093,10111,10129,1019...",NaN,10255,"10020,10133,10162,10182,10695",NaN,10199,NaN,NaN,NaN,10342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10199,10199,10199,NaN,NaN,NaN,NaN
8,7662,Capsicum annuum,L.,0.20,2.0,0.700000,NaN,NaN,NaN,NaN,NaN,present,3.0,3.0,3.0,NaN,1.50,NaN,2.50,NaN,3.0,NaN,NaN,absent,NaN,biotic,insect,insect,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.426,0.474,0.378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,9.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,1.0,NaN,2.0,1.0,1.0,NaN,NaN,NaN,NaN,"10111,10302,10315,10352,10353,10651","10111,10302,10315,10320,10328,10352,10353,10651","10199,10328,10353",NaN,NaN,NaN,NaN,NaN,10199,10328,10328.0,10328.0,NaN,10328,NaN,10293.0,NaN,10328,NaN,NaN,10328,NaN,"10199,10328",10328,10199,NaN,NaN,NaN,NaN
9,7666,Carallia brachiata,(Lour.) Merr.,3.00,33.0,11.750000,perennial,NaN,zoochorous,phanerophyte,evergreen,NaN,NaN,NaN,NaN,0.4,0.45,NaN,61.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400,0.598,0.391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,2.0,12.0,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10018,10319,10353","10018,10318,10319,10353","10199,10353","10018,10199,10243,10353,10177,10190,10203,1023...",NaN,10255,10177,10199,NaN,NaN,NaN,NaN,10353,10353,NaN,10293.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,7733,Cardiospermum halicacabum,L.,0.40,6.0,3.000000,NaN,NaN,anemochorous,NaN,deciduous,NaN,NaN,NaN,NaN,2.0,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.157,1.008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,"10018,10111","10018,10111,10319",10199,NaN,NaN,10255,NaN,10199,NaN,NaN,NaN,NaN,23,10353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,NaN
11,7766,Carex acutiformis,Ehrh.,0.30,1.2,0.750000,perennial,NaN,NaN,NaN,deciduous,absent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,absent,NaN,abiotic,wind,wind,NaN,70.35000,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.217,0.163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,1.0,7.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,1.0,1.0,NaN,1.0,NaN,NaN,"10111,10302,10315,10651","10111,10302,10315,10651",10191,"10111,10129,10233,10240,10302,10315,10651",NaN,NaN,NaN,10313,10313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10315,NaN,"10313,10315",10313,10315,NaN,10191.0,NaN,NaN
12,7875,Carex distans,L.,0.25,0.7,0.200000,perennial,NaN,NaN,NaN,evergreen,absent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,absent,NaN,abiotic,wind,wind,NaN,2.65250,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.102,0.091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,1.0,7.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,1.0,1.0,NaN,1.0,NaN,NaN,"10302,10315,10651","10302,10315,10651",10191,"10114,10129,10132,10240,10302,10315,10651",NaN,NaN,NaN,10313,10313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10315,NaN,"10313,10315",10313,10315,NaN,10191.0,NaN,NaN
13,7884,Carex echinata,Murray,0.10,0.4,0.303333,perennial,NaN,NaN,NaN,NaN,absent,2.0,2.0,NaN,NaN,NaN,NaN,0.77,NaN,2.0,NaN,monoecious,NaN,NaN,abiotic,wind,wind,NaN,2.18000,58,n,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,0.348,0.137,0.455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,6.0,3.0,8.0,NaN,NaN,NaN,NaN,2.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,4.0,3.0,1.0,NaN,1.0,1.0,1.0,"16,10302,10315,10651","10247,16,10302,10315,10328,10651","10129,10191,10328","10129,10132,16,10302,10315,10328,10337,10651",NaN,NaN,NaN,NaN,"10247,10313",10328,10328.0,NaN,NaN,NaN,NaN,10293.0,NaN,10328,NaN,10247,NaN,NaN,"10247,10313,10315,10328","10247,10313,10328",10315,NaN,10191.0,16,10337.0
14,7887,Carex elata,All.,0.30,1.0,0.900000,perennial,NaN,NaN,NaN,deciduous,absent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,absent,NaN,abiotic,wind,wind,NaN,26.93250,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.252,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,1.0,4.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,1.0,1.0,NaN,1.0,NaN,NaN,"10302,10315,10651","10302,10315,10651",10191,"10114,10302,10315,10651",NaN,NaN,NaN,10313,10313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10315,NaN,"10313,10315",10313,10315,NaN,10191.0,NaN,NaN
15,7893,Carex extensa,Gooden.,0.05,0.5,0.135000,perennial,NaN,hydrochorous,NaN,evergreen,absent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,monoecious,absent,NaN,abiotic,wind,wind,NaN,1.01250,NaN,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.471,0.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,1.0,6.0,NaN,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,3.0,3.0,1.0,NaN,1.0,NaN,NaN,"10315,10651","10247,10315,10651",10191,"10071,10114,10129,10240,10315,10651",NaN,10247,NaN,10313,"10247,10313",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10247,10315,NaN,"10247,10313,10315","10247,10313,10315",10315,NaN,10191.0,NaN,NaN
16,8029,Carex nigra,(L.) Reichard,0.05,0.8,0.110000,perennial,NaN,hydrochorous,NaN,deciduous,absent,NaN,NaN,NaN,NaN,NaN,NaN,0.64,NaN,NaN,NaN,monoecious,absent,NaN,abiotic,wind,wind,NaN,1.59177,NaN,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.701,0.391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,1.0,5.0,NaN,2.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,1.0,NaN,3.0,2.0,1.0,NaN,1.0,NaN,NaN,"10224,10302,10315,10651","10224,10247,10302,10315,10651",10191,"10129,10233,10302,10315,10651",NaN,"10247,10191",NaN,10313,"10247,10313",NaN,NaN,NaN,NaN,NaN,NaN,10293.0,NaN,NaN,NaN,10247,10315,NaN,"10247,10313,10315","10247,10313",10315,NaN,10191.0,NaN,NaN
17,8081,Carex punctata,Gaudin,0.15,1.0,0.420000,perennial,NaN,NaN,NaN,evergreen,absent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,monoecious,absent,NaN,abiotic,wind,wind,NaN,7.58000,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.471,0.500,0.943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,2.0,5.0,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,3.0,2.0,1.0,NaN,1.0,NaN,NaN,"10302,10315","10247,10302,10315,10328","10191,10328","10114,10132,10302,10315,10328",NaN,NaN,NaN,"10313,10328",10247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10247,"10315,10328",NaN,"10247,10315,10328","10247,10328",10315,NaN,10191.0,NaN,NaN
18,8094,Carex riparia,Curtis,0.60,1.5,1.050000,perennial,NaN,NaN,NaN,evergreen,absent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,absent,NaN,abiotic,wind,wind,NaN,140.70250,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.000,0.133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,1.0,5.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,1.0,1.0,NaN,1.0,NaN,NaN,"10302,10315,10651","10302,10315,10651",10191,"10114,10132,10302,10315,10651",NaN,NaN,NaN,10313,10313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10315,NaN,"10313,10315",10313,10315,NaN,10191.0,NaN,NaN
19,8096,Carex rostrata,Stokes,0.25,1.0,0.800000,perennial,NaN,hydrochorous,NaN,evergreen,absent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,absent,NaN,abiotic,wind,wind,NaN,11.82500,NaN,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,NaN,NaN,0.077,0.286,0.530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,2.0,5.0,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,1.0,1.0,NaN,1.0,NaN,NaN,"10224,10302,10315,10651","10224,10302,10315,10651","10129,10191","10129,10233,10302,10315,10651",NaN,10191,NaN,10313,10313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10315,NaN,"10313,10315",10313,10315,NaN,10191.0,NaN,NaN

In [55]:
# plant height
df_plant_height = df[[
    "work_species", 
    "trait_value_Plant_height_min",
    "trait_value_Plant_height_max",
    "trait_value_Plant_height_mean",
    "work_author"
]].copy()

df_plant_height["work_species"] = (df_plant_height["work_species"].astype(str).str.strip().str.lower())
df_plant_height = df_plant_height.dropna(subset=["trait_value_Plant_height_min", 
                                                 "trait_value_Plant_height_max",
                                                 "trait_value_Plant_height_mean"],
                                         how="all")

df_plant_height = df_plant_height.reset_index(drop=True)

df_plant_height

,work_species,trait_value_Plant_height_min,trait_value_Plant_height_max,trait_value_Plant_height_mean,work_author
0,aesculus hippocastanum,15.0,30.0,20.166667,L.
1,aquilaria yunnanensis,3.0,8.0,5.750000,S.C.Huang
2,bretschneidera sinensis,10.0,20.0,15.000000,Hemsl.
3,bruguiera gymnorhiza,7.0,36.0,15.000000,(L.) Lam.
4,bruguiera parviflora,1.0,24.0,24.000000,(Roxb.) Wight & Arn. ex Griff.
...,...,...,...,...,...
448,biancaea sappan,NaN,NaN,10.000000,(L.) Tod.
449,musella lasiocarpa,NaN,NaN,0.600000,(Franch.) C.Y.Wu ex H.W.Li
450,sideroxylon spinosum,NaN,NaN,7.000000,L.
451,microcos paniculata,NaN,NaN,15.000000,L.
452,fraxinus albicans,NaN,NaN,16.150000,Buckley

In [53]:
# SSD
df_ssd = df[[
    "work_species",
    "trait_value_SSD_mean",
    "work_author"
]].copy()

df_ssd["work_species"] = (df_ssd["work_species"].astype(str).str.strip().str.lower())
df_ssd = df_ssd.dropna(subset=["trait_value_SSD_mean"])

df_ssd = df_ssd.reset_index(drop=True)

df_ssd

,work_species,trait_value_SSD_mean,work_author
0,aesculus hippocastanum,510.0,L.
1,buxus sempervirens,910.0,L.
2,castanea sativa,500.0,Mill.
3,casuarina cunninghamiana,803.0,Miq.
4,casuarina equisetifolia,859.0,L.
...,...,...,...
65,liquidambar gracilipes,692.0,(Hemsl.) Ickert-Bond & J.Wen
66,liquidambar chinensis,727.0,Champ. ex Benth.
67,erythroxylum havanense,990.0,Jacq.
68,ormosia semicastrata,772.0,Hance
69,zenia insignis,409.0,Chun

In [51]:
# chromosone number
df_chrom = df[[
    "work_species", 
    "trait_value_Chromosome_number",
    "work_author"
]].copy()

df_chrom["work_species"] = (df_chrom["work_species"].astype(str).str.strip().str.lower())
df_chrom = df_chrom.dropna(subset=["trait_value_Chromosome_number"])

df_chrom = df_chrom.reset_index(drop=True)

df_chrom

,work_species,trait_value_Chromosome_number,work_author
0,cardiospermum halicacabum,22,L.
1,carex echinata,58,Murray
2,casuarina equisetifolia,18,L.
3,casuarina glauca,18,Sieber ex Spreng.
4,corymbia calophylla,22,(Lindl.) K.D.Hill & L.A.S.Johnson
5,cyperus esculentus,"96, 108, 208",L.
6,eleusine indica,"18,36,54",(L.) Gaertn.
7,epilobium ciliatum,18,Raf.
8,eucalyptus albens,22,Benth.
9,eucalyptus camaldulensis,"22, 28",Dehnh.
10,eucalyptus cladocalyx,"22, 24",F.Muell.
11,eucalyptus globulus,"20, 22, 28",Labill.
12,eucalyptus marginata,22,Donn ex Sm.
13,eucalyptus viminalis,22,Labill.
14,ficus microcarpa,24,L.f.
15,ilex aquifolium,"40, 46",L.
16,ilex paraguariensis,40,A.St.-Hil.
17,ipomoea aquatica,30,Forssk.
18,ipomoea triloba,30,L.
19,jatropha curcas,"22, 44, 88",L.
20,juncus effusus,"40, 42, 80",L.
21,kokia cookei,24,O.Deg.
22,melaleuca quinquenervia,22,(Cav.) S.T.Blake
23,melastoma sanguineum,56,Sims
24,melia azedarach,28,L.
25,morus alba,"14, 28, 42",L.
26,portulaca oleracea,"14,18,36,45,52,54",L.
27,spergularia marina,"18, 34, 36",(L.) Besser
28,syzygium malaccense,22,(L.) Merr. & L.M.Perry
29,trifolium pratense,"14, 28, 48",L.
30,trifolium subterraneum,"12, 16",L.
31,vicia sativa,"10, 12, 14, 18, 24",L.
32,vicia tenuifolia,"12, 14, 24",Roth
33,kokia drynarioides,24,(Seem.) Lewton

In [48]:
# lifecycle
df_l = df[[
    "work_species", 
    "trait_value_Lifecycle_1",
    "work_author"
]].copy()

df_l["work_species"] = (df_l["work_species"].astype(str).str.strip().str.lower())
df_l = df_l.dropna(subset=["trait_value_Lifecycle_1"])

df_l = df_l.reset_index(drop=True)

df_l

,work_species,trait_value_Lifecycle_1,work_author
0,aesculus hippocastanum,perennial,L.
1,aquilaria yunnanensis,perennial,S.C.Huang
2,bretschneidera sinensis,perennial,Hemsl.
3,bruguiera gymnorhiza,perennial,(L.) Lam.
4,bruguiera parviflora,perennial,(Roxb.) Wight & Arn. ex Griff.
...,...,...,...
442,forsythia ovata,perennial,Nakai
443,sarracenia psittacina,perennial,Michx.
444,aegilops sharonensis,annual,Eig
445,hygrophila difformis,perennial,(L.f.) Blume
446,solanum pennellii,perennial,Correll

In [47]:
# seed length
df_sl = df[[
    "work_species", 
    "trait_value_Seed_length_max",
    "trait_value_Seed_length_mean",
    "trait_value_Seed_length_min",
    "work_author"
]].copy()

df_sl["work_species"] = (df_sl["work_species"].astype(str).str.strip().str.lower())
df_sl = df_sl.dropna(subset=["trait_value_Seed_length_max", 
                            "trait_value_Seed_length_mean",
                            "trait_value_Seed_length_min"],
                    how="all")

df_sl = df_sl.reset_index(drop=True)

df_sl

,work_species,trait_value_Seed_length_max,trait_value_Seed_length_mean,trait_value_Seed_length_min,work_author
0,buxus sempervirens,5.000,5.000,5.000,L.
1,capsicum annuum,3.000,3.000,3.000,L.
2,carex echinata,2.000,2.000,2.000,Murray
3,casuarina cunninghamiana,5.000,5.000,5.000,Miq.
4,casuarina equisetifolia,7.000,NaN,6.000,L.
...,...,...,...,...,...
61,trichilia hirta,4.246,4.246,4.246,L.
62,pouteria glomerata,30.000,NaN,15.000,(Miq.) Radlk.
63,jacaranda copaia,30.000,NaN,1.000,(Aubl.) D.Don
64,erythroxylum macrophyllum,30.000,NaN,1.000,Cav.
65,erythroxylum fimbriatum,30.000,NaN,15.000,Peyr.

In [46]:
# reproduction sexual
df_rs = df[[
    "work_species",
    "trait_value_Reproduction_sexual_1",
    "work_author"
]].copy()

df_rs["work_species"] = (df_rs["work_species"].astype(str).str.strip().str.lower())
df_rs = df_rs.dropna(subset=["trait_value_Reproduction_sexual_1"])

df_rs = df_rs.reset_index(drop=True)

df_rs

              work_species trait_value_Reproduction_sexual_1       work_author
0       buxus sempervirens                        monoecious                L.
1           carex echinata                        monoecious            Murray
2            carex extensa                        monoecious           Gooden.
3              carex nigra                        monoecious     (L.) Reichard
4           carex punctata                        monoecious            Gaudin
..                     ...                               ...               ...
65     medicago truncatula                          bisexual           Gaertn.
66        picea sitchensis                        monoecious  (Bong.) Carrière
67            quercus ilex                        monoecious                L.
68   rubus hochstetterorum                          bisexual             Seub.
69  vaccinium cylindraceum                          bisexual               Sm.

[70 rows x 3 columns]

In [45]:
# leaf size
df_ls = df[[
    "work_species",
    "trait_value_Leaf_size_mean", 
    "work_author"
]].copy()

df_ls["work_species"] = (df_ls["work_species"].astype(str).str.strip().str.lower())
df_ls = df_ls.dropna(subset=["trait_value_Leaf_size_mean"])

df_ls = df_ls.reset_index(drop=True)

df_ls

               work_species  trait_value_Leaf_size_mean       work_author
0    aesculus hippocastanum                    65.28700                L.
1        buxus sempervirens                     1.38750                L.
2         carex acutiformis                    70.35000             Ehrh.
3             carex distans                     2.65250                L.
4            carex echinata                     2.18000            Murray
..                      ...                         ...               ...
78          viola palustris                    18.12917                L.
79     caragana arborescens                    10.59500              Lam.
80         picea sitchensis                     0.18100  (Bong.) Carrière
81             quercus ilex                     8.51000                L.
82  erythroxylum mucronatum                    36.20400            Benth.

[83 rows x 3 columns]

In [57]:
df_ls.to_csv("GIFT-db_leaf_size.csv", index=False)
df_sl.to_csv("GIFT-db_seed_length.csv", index=False)
df_plant_height.to_csv("GIFT-db_plant_height.csv", index=False)
df_ssd.to_csv("GIFT-db_stem_wood_density.csv", index=False)
df_chrom.to_csv("GIFT-db_chromosome_number.csv", index=False)
df_l.to_csv("GIFT-db_lifecycle.csv", index=False)
df_rs.to_csv("GIFT-db_reproduction_sexual.csv", index=False)