In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("leaf_area.txt", sep='\t', encoding='latin-1')
df.head(20)

,LastName,FirstName,DatasetID,Dataset,SpeciesName,AccSpeciesID,AccSpeciesName,ObservationID,ObsDataID,TraitID,TraitName,DataID,DataName,OriglName,OrigValueStr,OrigUnitStr,ValueKindName,OrigUncertaintyStr,UncertaintyName,Replicates,StdValue,UnitName,RelUncertaintyPercent,OrigObsDataID,ErrorRisk,Reference,Comment,StdValueStr,Unnamed: 28
0,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007358,NaN,NaN,193,Vegetation type / Biome,bog,no bog,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",NaN,NaN,NaN
1,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007360,3108.0,"Leaf area (in case of compound leaves: leaf, p...",6575,Leaf area: in case of compound leaves leaf; pe...,leaf.surface (cm2),29.7717,cm2,Single,NaN,NaN,NaN,2977.17,mm2,NaN,NaN,4.29420,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",leaf.surface (cm2): leaf surface,NaN,NaN
2,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007367,NaN,NaN,59,Latitude,Lat,-45.4,degree,NaN,NaN,NaN,NaN,45.40,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",Lat,NaN,NaN
3,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007368,NaN,NaN,60,Longitude,Lon,-71.8,degree,NaN,NaN,NaN,NaN,-71.80,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",Lon,NaN,NaN
4,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007369,NaN,NaN,61,Altitude,Alt,170,m,NaN,NaN,NaN,NaN,170.00,m,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",Alt,NaN,NaN
5,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007370,NaN,NaN,211,Sampling date: month,Time,September,month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",Time,NaN,NaN
6,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007371,NaN,NaN,112,Location Site ID,Location,Shipley_Sherbrooke,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",Location,Shipley_Sherbrooke,NaN
7,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007372,NaN,NaN,62,Mean annual temperature (MAT),MAT,4.525,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",MAT,NaN,NaN
8,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007373,NaN,NaN,77,Mean temperature during growth season,gs_temp,13.6833333333333,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",gs_temp,NaN,NaN
9,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007374,NaN,NaN,80,Mean sum of annual precipitation (PPT / MAP / ...,ann_rain,1109.806,mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",ann_rain,NaN,NaN
10,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93211,1007375,NaN,NaN,81,Mean sum of precipitation during growth season,gs_rain,631.7,mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",gs_rain,NaN,NaN
11,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93212,1007378,NaN,NaN,193,Vegetation type / Biome,bog,no bog,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",NaN,NaN,NaN
12,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93212,1007380,3108.0,"Leaf area (in case of compound leaves: leaf, p...",6575,Leaf area: in case of compound leaves leaf; pe...,leaf.surface (cm2),42.3843,cm2,Single,NaN,NaN,NaN,4238.43,mm2,NaN,NaN,3.45536,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",leaf.surface (cm2): leaf surface,NaN,NaN
13,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93212,1007387,NaN,NaN,59,Latitude,Lat,-45.4,degree,NaN,NaN,NaN,NaN,45.40,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",Lat,NaN,NaN
14,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93212,1007388,NaN,NaN,60,Longitude,Lon,-71.8,degree,NaN,NaN,NaN,NaN,-71.80,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",Lon,NaN,NaN
15,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93212,1007389,NaN,NaN,61,Altitude,Alt,170,m,NaN,NaN,NaN,NaN,170.00,m,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",Alt,NaN,NaN
16,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93212,1007390,NaN,NaN,211,Sampling date: month,Time,September,month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",Time,NaN,NaN
17,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93212,1007391,NaN,NaN,112,Location Site ID,Location,Shipley_Sherbrooke,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",Location,Shipley_Sherbrooke,NaN
18,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93212,1007392,NaN,NaN,62,Mean annual temperature (MAT),MAT,4.525,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",MAT,NaN,NaN
19,Shipley,Bill,50,Leaf and Whole Plant Traits Database,Fraxinus americana,25239,Fraxinus americana,93212,1007393,NaN,NaN,77,Mean temperature during growth season,gs_temp,13.6833333333333,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Shipley, B. and T. T. Vu. 2002. Dry matter con...",gs_temp,NaN,NaN

In [4]:
df_trait_id = df[df["TraitID"].notna()]

In [9]:
df_trait_id_non_nan = df_trait_id[df_trait_id['StdValue'].notna()]

df_trait_id_non_nan.loc[:, "AccSpeciesName"] = (
    df_trait_id_non_nan["AccSpeciesName"].str.lower()
)

df_grouped = df_trait_id_non_nan.groupby("AccSpeciesName", as_index=False).agg(
    leaf_area_mean_g_mm2=("StdValue", "mean"),
    leaf_area_max_g_mm2=("StdValue", "max"),
    leaf_area_min_g_mm2=("StdValue", "min"),
    references=("Reference", lambda x: "; ".join(x.dropna().unique()))
)
df_grouped

,AccSpeciesName,leaf_area_mean_g_mm2,leaf_area_max_g_mm2,leaf_area_min_g_mm2,references
0,carex nigra,895.328606,1143.457211,647.200000,"Díaz, S., J. G. Hodgson, K. Thompson, M. Cabid..."
1,carex rostrata,1124.923333,1602.000000,660.400000,"Dalke, I.V., Novakovskiy, A.B., Maslova, S.P. ..."
2,centella asiatica,1722.570913,3326.151054,208.850000,"Schellenberger Costa, D., Classen, A., Ferger,..."
3,cercis canadensis,5849.663404,17158.000000,727.506816,"Cavender-Bares, J., A. Keen, and B. Miles. 200..."
4,chamaecyparis obtusa,211.464667,441.800000,56.100000,Feng Y & van Kleunen M (2014) Responses to sha...
5,colocasia esculenta,282982.070545,547073.138896,161907.618269,"Schellenberger Costa, D., Classen, A., Ferger,..."
6,comarum palustre,6405.959829,14972.400000,1930.600000,"Dalke, I.V., Novakovskiy, A.B., Maslova, S.P. ..."
7,cornus florida,5078.523810,8523.000000,2526.000000,"Cavender-Bares, J., A. Keen, and B. Miles. 200..."
8,corylus avellana,4060.000000,4060.000000,4060.000000,"Díaz, S., J. G. Hodgson, K. Thompson, M. Cabid..."
9,cryptomeria japonica,148.118000,324.600000,22.900000,Feng Y & van Kleunen M (2014) Responses to sha...
10,cunninghamia lanceolata,205.496154,543.650000,18.300000,Feng Y & van Kleunen M (2014) Responses to sha...
11,daucus carota,4718.246099,19303.100000,352.600000,"unpub.; Isaac, M.E., Martin, A.R. Accumulating..."
12,dicorynia guianensis,5152.816669,15836.666667,1356.666667,"Baraloto, C., C. E. T. Paine, L. Poorter, J. B..."
13,eperua falcata,11982.669903,66644.800000,1306.666667,"Baraloto, C., C. E. T. Paine, L. Poorter, J. B..."
14,epilobium ciliatum,110.000000,110.000000,110.000000,"Shipley, B. 1995. Structured Interspecific Det..."
15,epilobium hirsutum,1900.300000,2833.000000,967.600000,"Díaz, S., J. G. Hodgson, K. Thompson, M. Cabid..."
16,eriophorum vaginatum,271.369740,389.200000,114.800000,Soudzilovskaia et al 2013 Functional traits pr...
17,fagus sylvatica,2027.700000,2027.700000,2027.700000,"Díaz, S., J. G. Hodgson, K. Thompson, M. Cabid..."
18,ficus benjamina,586.750000,608.000000,562.000000,unpub.
19,filipendula ulmaria,14792.456883,37255.400000,3958.200000,"Dalke, I.V., Novakovskiy, A.B., Maslova, S.P. ..."
20,frangula alnus,3947.099000,5360.370000,2560.000000,"Shipley, B. and T. T. Vu. 2002. Dry matter con..."
21,frangula azorica,2997.816667,2997.816667,2997.816667,"Onstein, R.E., Linder, H.P. (2016). Beyond cli..."
22,fraxinus americana,22352.719818,49622.000000,992.870000,"Shipley, B. and T. T. Vu. 2002. Dry matter con..."
23,fraxinus excelsior,16047.000000,16047.000000,16047.000000,"Díaz, S., J. G. Hodgson, K. Thompson, M. Cabid..."
24,fraxinus mandshurica,4120.534667,6082.200000,1699.380000,Feng Y & van Kleunen M (2014) Responses to sha...
25,fraxinus nigra,4032.142857,5387.000000,2976.000000,DOI: 10.5281/zenodo.3258342
26,geum rivale,7792.284587,21788.900000,2721.200000,"Díaz, S., J. G. Hodgson, K. Thompson, M. Cabid..."
27,ginkgo biloba,2305.000000,2558.000000,2065.000000,unpub.
28,hamamelis virginiana,2190.863636,3552.000000,1168.000000,"Cavender-Bares, J., A. Keen, and B. Miles. 200..."

In [10]:
df_grouped.to_csv("leaf_area_cleaned.csv", index=False)