In [2]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("TR8_db_extracted_traits.csv")
df.head(20)

,scientific_name,LEDA_First_Flowering,LEDA_Dispersal,LEDA_Growth_Form,LEDA_Lifespan,LEDA_Seed_Mass,LEDA_Woodiness,ECO_Height_Max,ECO_Height_Min,ECO_Life_Form,ECO_Pollen_Vector,ECO_Seed_Weight,PIGNATTI_Life_Form
0,Buxus sempervirens,NaN,NaN,NaN,NaN,NaN,NaN,500,200.0,phanerophyte,insect,13.1;13.9,NP (SV)
1,Capsicum annuum,Within 1 year,NaN,NaN,summer annuals + strict monocarpic bi-annuals ...,NaN,non-woody,NaN,NaN,NaN,NaN,6,T SCAP
2,Carex acutiformis,NaN,NaN,NaN,NaN,NaN,NaN,150,60.0,helophyte,wind,1.11;1.15,G RHIZ
3,Carex distans,Between 1 and 5 years,autochor + epizoochor + meteorochor + nautochor,Hemicryptophyte,perennials,NaN,non-woody,100,15.0,hemicryptophyte,wind,1.14;1.38,H CAESP
4,Carex echinata,Between 1 and 5 years,autochor + endozoochor + epizoochor + nautochor,Hemicryptophyte,perennials,NaN,non-woody,40,10.0,helophyte;hemicryptophyte,wind,0.84,NaN
5,Carex elata,Between 1 and 5 years,autochor + dysochor + epizoochor + meteorochor...,Hemicryptophyte + Hydrophyte,perennials,NaN,non-woody,90,NaN,helophyte;hemicryptophyte,wind,0.67,NaN
6,Carex extensa,Within 1 year + Between 1 and 5 years,autochor + epizoochor + nautochor,Hemicryptophyte,perennials,NaN,non-woody,40,5.0,hemicryptophyte,wind,1.1,H CAESP
7,Carex nigra,NaN,NaN,NaN,NaN,NaN,NaN,70,7.0,helophyte;hemicryptophyte,wind,0.69;0.81,NaN
8,Carex punctata,NaN,NaN,NaN,NaN,NaN,NaN,80,NaN,hemicryptophyte,wind,1.2592,H CAESP
9,Carex riparia,NaN,NaN,NaN,NaN,NaN,NaN,160,100.0,helophyte;hemicryptophyte,wind,2.5948;2.6,G RHIZ
10,Carex rostrata,NaN,NaN,NaN,NaN,NaN,NaN,100,20.0,helophyte,wind,1.1;1.216,G RHIZ
11,Castanea sativa,Over 5 years,agochor + autochor + dysochor + ethelochor + h...,Phanerophyte,perennials,NaN,woody,3000,NaN,phanerophyte,insect,4050;9944,P SCAP
12,Ceratonia siliqua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P CAESP (SV)
13,Chamaerops humilis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P SCAP (SV)
14,Comarum palustre,NaN,NaN,NaN,NaN,NaN,NaN,45,15.0,helophyte,insect;insect,0.32;0.4,NaN
15,Corrigiola litoralis,NaN,NaN,NaN,NaN,NaN,NaN,25,5.0,therophyte,selfed,0.3;0.39,T SCAP
16,Corylus avellana,Within 1 year + Over 5 years,agochor + autochor + dysochor + endozoochor + ...,Phanerophyte,perennials + poly-annuals > 50 years (long-liv...,NaN,woody,600,100.0,phanerophyte,wind,1080;1097.3,P CAESP
17,Corylus colurna,Within 1 year,NaN,NaN,perennials,NaN,woody,NaN,NaN,NaN,NaN,1801,NaN
18,Crataegus laevigata,NaN,NaN,NaN,NaN,NaN,NaN,1000,200.0,phanerophyte,insect,60.1;60.1;63.8,NaN
19,Cupressus sempervirens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P SCAP (SV)

In [4]:
# df[["scientific_name", "ECO_Height_Max", "ECO_Height_Min", "LEDA_Lifespan"]]
df["scientific_name"] = df["scientific_name"].str.lower()

df["ECO_Height_Max"] = pd.to_numeric(df["ECO_Height_Max"], errors="coerce")
df["ECO_Height_Min"] = pd.to_numeric(df["ECO_Height_Min"], errors="coerce")

# height
df["ECO_Height_Mean"] = df[["ECO_Height_Max", "ECO_Height_Min"]].mean(axis=1)
df_height = (
    df.groupby("scientific_name", as_index=False)
      .agg(
          height_max=("ECO_Height_Max", "max"),
          height_min=("ECO_Height_Min", "min"),
          height_mean=("ECO_Height_Mean", "mean")
      )
)


df_height

            scientific_name  height_max  height_min  height_mean
0    aesculus hippocastanum        25.0         NaN         25.0
1        buxus sempervirens       500.0       200.0        350.0
2           capsicum annuum         NaN         NaN          NaN
3         carex acutiformis       150.0        60.0        105.0
4             carex distans       100.0        15.0         57.5
..                      ...         ...         ...          ...
126            vicia sativa       120.0        15.0         67.5
127        vicia tenuifolia        60.0         NaN         60.0
128         viola palustris         NaN         NaN          NaN
129         ziziphus jujuba         NaN         NaN          NaN
130          zostera marina        50.0        20.0         35.0

[131 rows x 4 columns]

In [5]:
df_height.to_csv("TR8_db_df_height.csv", index=False)

In [6]:
def mode_or_nan(s):
    m = s.dropna().mode()
    return m.iloc[0] if not m.empty else pd.NA

df_lifespan = (
    df.groupby("scientific_name", as_index=False)
      .agg(
          lifespan=("LEDA_Lifespan", mode_or_nan)
      )
)
df_lifespan

            scientific_name                                           lifespan
0    aesculus hippocastanum    poly-annuals < 5 years (short-lived perennials)
1        buxus sempervirens                                               <NA>
2           capsicum annuum  summer annuals + strict monocarpic bi-annuals ...
3         carex acutiformis                                               <NA>
4             carex distans                                         perennials
..                      ...                                                ...
126            vicia sativa  annuals + perennials + summer annuals + winter...
127        vicia tenuifolia                                               <NA>
128         viola palustris                                         perennials
129         ziziphus jujuba                                               <NA>
130          zostera marina                                               <NA>

[131 rows x 2 columns]

In [7]:
df["LEDA_Lifespan"].dropna().unique()

array(['summer annuals + strict monocarpic bi-annuals and poly-annuals',
       'perennials',
       'perennials + poly-annuals > 50 years (long-lived perennials)',
       'summer annuals',
       'perennials + poly-annuals 5-50 years (medium-lived perennials)',
       'perennials + poly-annuals < 5 years (short-lived perennials) + poly-annuals 5-50 years (medium-lived perennials)',
       'poly-annuals 5-50 years (medium-lived perennials)', 'annuals',
       'annuals + summer annuals',
       'annuals + perennials + strict monocarpic bi-annuals and poly-annuals + poly-annuals < 5 years (short-lived perennials)',
       'annuals + perennials + poly-annuals < 5 years (short-lived perennials)',
       'annuals + perennials + summer annuals + winter annuals + strict monocarpic bi-annuals and poly-annuals',
       'poly-annuals < 5 years (short-lived perennials)'], dtype=object)

In [8]:
df[df["LEDA_Lifespan"]=="annuals + perennials + summer annuals + winter annuals + strict monocarpic bi-annuals and poly-annuals"]

,scientific_name,LEDA_First_Flowering,LEDA_Dispersal,LEDA_Growth_Form,LEDA_Lifespan,LEDA_Seed_Mass,LEDA_Woodiness,ECO_Height_Max,ECO_Height_Min,ECO_Life_Form,ECO_Pollen_Vector,ECO_Seed_Weight,PIGNATTI_Life_Form,ECO_Height_Mean
119,vicia sativa,Within 1 year + Between 1 and 5 years,autochor + ballochor + endozoochor + speirochor,Liana + Therophyte,annuals + perennials + summer annuals + winter...,NaN,non-woody,120.0,15.0,therophyte,insect,18.2;33.5,T SCAP,67.5

In [13]:
df = df.copy()

df.loc[:, "LEDA_Lifespan_clean"] = (
    df["LEDA_Lifespan"]
    .str.extract(r"\(([^)]+)\)", expand=False)
)

lifespan_map = {
    "perennials": "perennial",
    "summer annuals": "annual",
    "annuals + summer annuals": "annual",
    "summer annuals + strict monocarpic bi-annuals and poly-annuals": "annual",
    "annuals": "annual"
}

df.loc[df["LEDA_Lifespan_clean"].isna(), "LEDA_Lifespan_clean"] = (
    df.loc[df["LEDA_Lifespan_clean"].isna(), "LEDA_Lifespan"]
      .map(lifespan_map)
)
df_check = df[df["LEDA_Lifespan"].notna()]
df_check = df_check[["scientific_name", "LEDA_Lifespan_clean"]]
df_check

              scientific_name      LEDA_Lifespan_clean
1             capsicum annuum                   annual
3               carex distans                perennial
4              carex echinata                perennial
5                 carex elata                perennial
6               carex extensa                perennial
11            castanea sativa                perennial
16           corylus avellana    long-lived perennials
17            corylus colurna                perennial
25            eleusine indica                   annual
26         epilobium ciliatum                perennial
27         epilobium hirsutum  medium-lived perennials
28   eriophorum angustifolium  medium-lived perennials
29       eriophorum vaginatum  medium-lived perennials
31            fagus sylvatica                perennial
33        filipendula ulmaria   short-lived perennials
34             frangula alnus                perennial
36                geum rivale  medium-lived perennials
38            hordeum marinum                   annual
39         hottonia palustris  medium-lived perennials
40            ilex aquifolium                perennial
41     impatiens noli-tangere                   annual
42              juglans regia                perennial
43             juncus effusus                perennial
45            lathyrus aphaca                   annual
49          lobelia dortmanna                perennial
51      lupinus angustifolius                   annual
52             lupinus luteus                   annual
54     lysimachia thyrsiflora                perennial
55       lythrum hyssopifolia                   annual
57            mentha aquatica                perennial
58          mentha longifolia                perennial
67         phaseolus vulgaris                   annual
68       phragmites australis                perennial
71             plantago major   short-lived perennials
72         portulaca oleracea                   annual
75               prunus avium                perennial
82            quercus petraea    long-lived perennials
83              quercus robur                perennial
84              quercus rubra                perennial
88               salix caprea                perennial
92             sambucus nigra                perennial
101        sparganium erectum                perennial
110        trifolium pratense                perennial
111    trifolium subterraneum                   annual
113           typha latifolia                perennial
115     vaccinium vitis-idaea                perennial
117    veronica serpyllifolia   short-lived perennials
119              vicia sativa                      NaN
121           viola palustris                perennial
128        fraxinus excelsior    long-lived perennials
130    aesculus hippocastanum   short-lived perennials

In [17]:
df_check.count()

scientific_name        51
LEDA_Lifespan_clean    50
dtype: int64

In [18]:
df_check.to_csv("TR8_db_lifespan.csv", index=False)