In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("ssd.txt", sep='\t', encoding='latin-1')
df.head(20)

,LastName,FirstName,DatasetID,Dataset,SpeciesName,AccSpeciesID,AccSpeciesName,ObservationID,ObsDataID,TraitID,TraitName,DataID,DataName,OriglName,OrigValueStr,OrigUnitStr,ValueKindName,OrigUncertaintyStr,UncertaintyName,Replicates,StdValue,UnitName,RelUncertaintyPercent,OrigObsDataID,ErrorRisk,Reference,Comment,StdValueStr,Unnamed: 28
0,Cornelissen,Johannes,37,Sheffield Database,Fraxinus excelsior,25247,Fraxinus excelsior,16023,454175,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,650,kg/m3,Single,NaN,NaN,NaN,0.65,g/cm3,NaN,5828201.0,1.852130,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
1,Cornelissen,Johannes,37,Sheffield Database,Fraxinus excelsior,25247,Fraxinus excelsior,16023,454176,NaN,NaN,113,Reference / source,Reference,(Brzeziecki & Kienast 94),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,1107,NaN
2,Cornelissen,Johannes,37,Sheffield Database,Fagus sylvatica,23906,Fagus sylvatica,16027,454183,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,680,kg/m3,Single,NaN,NaN,NaN,0.68,g/cm3,NaN,5827030.0,0.408622,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
3,Cornelissen,Johannes,37,Sheffield Database,Fagus sylvatica,23906,Fagus sylvatica,16027,454184,NaN,NaN,113,Reference / source,Reference,(Brzeziecki & Kienast 94),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,1107,NaN
4,Cornelissen,Johannes,37,Sheffield Database,Frangula alnus,25217,Frangula alnus,16034,454197,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,580,kg/m3,Single,NaN,NaN,NaN,0.58,g/cm3,NaN,NaN,1.166590,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
5,Cornelissen,Johannes,37,Sheffield Database,Frangula alnus,25217,Frangula alnus,16034,454198,NaN,NaN,113,Reference / source,Reference,"Schütt et al. 1994, Enzyklopädie der Holzgewächse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,7569,NaN
6,Cornelissen,Johannes,37,Sheffield Database,Corylus avellana,14688,Corylus avellana,16036,454201,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,600,kg/m3,Single,NaN,NaN,NaN,0.60,g/cm3,NaN,5836781.0,1.867150,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
7,Cornelissen,Johannes,37,Sheffield Database,Corylus avellana,14688,Corylus avellana,16036,454202,NaN,NaN,113,Reference / source,Reference,"Schütt et al. 1994, Enzyklopädie der Holzgewächse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,7569,NaN
8,Cornelissen,Johannes,37,Sheffield Database,Fraxinus excelsior,25247,Fraxinus excelsior,16039,454207,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,650,kg/m3,Single,NaN,NaN,NaN,0.65,g/cm3,NaN,NaN,1.852130,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
9,Cornelissen,Johannes,37,Sheffield Database,Fraxinus excelsior,25247,Fraxinus excelsior,16039,454208,NaN,NaN,113,Reference / source,Reference,"Schütt et al. 1994, Enzyklopädie der Holzgewächse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,7569,NaN
10,Cornelissen,Johannes,37,Sheffield Database,Fagus sylvatica,23906,Fagus sylvatica,16040,454209,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,680,kg/m3,Single,NaN,NaN,NaN,0.68,g/cm3,NaN,NaN,0.408622,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
11,Cornelissen,Johannes,37,Sheffield Database,Fagus sylvatica,23906,Fagus sylvatica,16040,454210,NaN,NaN,113,Reference / source,Reference,"Schütt et al. 1994, Enzyklopädie der Holzgewächse",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,7569,NaN
12,Kleyer,Michael,25,The LEDA Traitbase,Aesculus hippocastanum,1571,Aesculus hippocastanum,212852,2269667,NaN,NaN,398,Measurement method 1: method of sampling and m...,general method,actual measurement (following LEDA data standa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
13,Kleyer,Michael,25,The LEDA Traitbase,Aesculus hippocastanum,1571,Aesculus hippocastanum,212852,2269669,NaN,NaN,213,Number of replicates,number of replicates,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
14,Kleyer,Michael,25,The LEDA Traitbase,Aesculus hippocastanum,1571,Aesculus hippocastanum,212852,2269670,NaN,NaN,400,Validity,valid,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
15,Kleyer,Michael,25,The LEDA Traitbase,Aesculus hippocastanum,1571,Aesculus hippocastanum,212852,2269672,NaN,NaN,401,LEDA SBS number,SBS number,24982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
16,Kleyer,Michael,25,The LEDA Traitbase,Aesculus hippocastanum,1571,Aesculus hippocastanum,212852,2269673,NaN,NaN,413,Plant developmental status / plant age / matur...,plant stage,adult,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,mature,NaN
17,Kleyer,Michael,25,The LEDA Traitbase,Aesculus hippocastanum,1571,Aesculus hippocastanum,212852,2269674,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],510,g/dm3,Mean,NaN,NaN,NaN,0.51,g/cm3,NaN,NaN,5.722660,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
18,Kleyer,Michael,25,The LEDA Traitbase,Aesculus hippocastanum,1571,Aesculus hippocastanum,212852,2269675,NaN,NaN,235,"Comments, notes, methods",general comment,Moisture content 15%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
19,Kleyer,Michael,25,The LEDA Traitbase,Buxus sempervirens,8964,Buxus sempervirens,213511,2274891,NaN,NaN,398,Measurement method 1: method of sampling and m...,general method,actual measurement (following LEDA data standa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN

In [8]:
df.groupby("AccSpeciesName").size()

AccSpeciesName
Aegle marmelos                 4
Aesculus hippocastanum        14
Angophora floribunda           6
Aquilaria malaccensis          5
Aquilaria sinensis             8
                              ..
Handroanthus impetiginosus    33
Heritiera fomes                2
Heritiera littoralis          12
Heteromeles arbutifolia        6
Hevea brasiliensis            94
Length: 137, dtype: int64

In [5]:
df = df[df["TraitID"].notna()]
df.head(20)

,LastName,FirstName,DatasetID,Dataset,SpeciesName,AccSpeciesID,AccSpeciesName,ObservationID,ObsDataID,TraitID,TraitName,DataID,DataName,OriglName,OrigValueStr,OrigUnitStr,ValueKindName,OrigUncertaintyStr,UncertaintyName,Replicates,StdValue,UnitName,RelUncertaintyPercent,OrigObsDataID,ErrorRisk,Reference,Comment,StdValueStr,Unnamed: 28
0,Cornelissen,Johannes,37,Sheffield Database,Fraxinus excelsior,25247,Fraxinus excelsior,16023,454175,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,650,kg/m3,Single,NaN,NaN,NaN,0.650000,g/cm3,NaN,5828201.0,1.852130,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
2,Cornelissen,Johannes,37,Sheffield Database,Fagus sylvatica,23906,Fagus sylvatica,16027,454183,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,680,kg/m3,Single,NaN,NaN,NaN,0.680000,g/cm3,NaN,5827030.0,0.408622,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
4,Cornelissen,Johannes,37,Sheffield Database,Frangula alnus,25217,Frangula alnus,16034,454197,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,580,kg/m3,Single,NaN,NaN,NaN,0.580000,g/cm3,NaN,NaN,1.166590,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
6,Cornelissen,Johannes,37,Sheffield Database,Corylus avellana,14688,Corylus avellana,16036,454201,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,600,kg/m3,Single,NaN,NaN,NaN,0.600000,g/cm3,NaN,5836781.0,1.867150,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
8,Cornelissen,Johannes,37,Sheffield Database,Fraxinus excelsior,25247,Fraxinus excelsior,16039,454207,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,650,kg/m3,Single,NaN,NaN,NaN,0.650000,g/cm3,NaN,NaN,1.852130,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
10,Cornelissen,Johannes,37,Sheffield Database,Fagus sylvatica,23906,Fagus sylvatica,16040,454209,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood density,680,kg/m3,Single,NaN,NaN,NaN,0.680000,g/cm3,NaN,NaN,0.408622,"Cornelissen, J. H. C., B. Cerabolini, P. Castr...",NaN,NaN,NaN
17,Kleyer,Michael,25,The LEDA Traitbase,Aesculus hippocastanum,1571,Aesculus hippocastanum,212852,2269674,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],510,g/dm3,Mean,NaN,NaN,NaN,0.510000,g/cm3,NaN,NaN,5.722660,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
24,Kleyer,Michael,25,The LEDA Traitbase,Buxus sempervirens,8964,Buxus sempervirens,213511,2274898,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],910,g/dm3,Mean,NaN,NaN,NaN,0.910000,g/cm3,NaN,NaN,1.428270,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
31,Kleyer,Michael,25,The LEDA Traitbase,Castanea sativa,11068,Castanea sativa,213827,2277425,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],500,g/dm3,Mean,NaN,NaN,NaN,0.500000,g/cm3,NaN,5841418.0,1.548970,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
38,Kleyer,Michael,25,The LEDA Traitbase,Fagus sylvatica,23906,Fagus sylvatica,214653,2283964,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],650,g/dm3,Mean,NaN,NaN,NaN,0.650000,g/cm3,NaN,NaN,0.352692,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
45,Kleyer,Michael,25,The LEDA Traitbase,Fagus sylvatica,23906,Fagus sylvatica,214654,2283974,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],670,g/dm3,Mean,NaN,NaN,NaN,0.670000,g/cm3,NaN,5827641.0,0.390258,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
53,Kleyer,Michael,25,The LEDA Traitbase,Fraxinus excelsior,25247,Fraxinus excelsior,214755,2284774,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],690,g/dm3,Mean,NaN,NaN,NaN,0.690000,g/cm3,NaN,5839501.0,2.056960,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
54,Kleyer,Michael,25,The LEDA Traitbase,Fraxinus excelsior,25247,Fraxinus excelsior,1123172,2284775,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],830,g/dm3,Maximum,NaN,NaN,NaN,0.830000,g/cm3,NaN,5831694.0,2.690560,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
55,Kleyer,Michael,25,The LEDA Traitbase,Fraxinus excelsior,25247,Fraxinus excelsior,1123173,2284776,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],510,g/dm3,Minimum,NaN,NaN,NaN,0.510000,g/cm3,NaN,NaN,1.020200,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
62,Kleyer,Michael,25,The LEDA Traitbase,Fraxinus excelsior,25247,Fraxinus excelsior,214756,2284786,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],640,g/dm3,Mean,NaN,NaN,NaN,0.640000,g/cm3,NaN,5827189.0,1.798960,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
69,Kleyer,Michael,25,The LEDA Traitbase,Fraxinus pennsylvanica,25263,Fraxinus pennsylvanica,214765,2284856,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],719,g/dm3,Maximum,NaN,NaN,NaN,0.719000,g/cm3,NaN,NaN,5.913760,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
70,Kleyer,Michael,25,The LEDA Traitbase,Fraxinus pennsylvanica,25263,Fraxinus pennsylvanica,1123174,2284857,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,mean SSD [g/cm^3],600,g/dm3,Minimum,NaN,NaN,NaN,0.600000,g/cm3,NaN,NaN,5.124200,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ...",NaN,NaN,NaN
76,Cornwell,Will,55,Jasper Ridge Californian Woody Plants Database,Heteromeles arbutifolia,28615,Heteromeles arbutifolia,218198,2312243,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,wood.density,0.62,g / cm3,Single,NaN,NaN,NaN,0.620000,g/cm3,NaN,NaN,1.041960,"Preston, K. A., W. K. Cornwell, and J. L. DeNo...","wood density, sampled on third year shoots",NaN,NaN
84,Lloyd,Jon,34,The RAINFOR Plant Trait Database,Dipteryx alata,18796,Dipteryx alata,251789,2441568,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood Dens g/cm3,0.739944792220054,g/cm3,Single,NaN,NaN,NaN,0.739945,g/cm3,NaN,NaN,0.967785,"Fyllas, N. M., S. Patino, T. R. Baker, G. Biel...",NaN,NaN,NaN
92,Lloyd,Jon,34,The RAINFOR Plant Trait Database,Hevea brasiliensis,28671,Hevea brasiliensis,252024,2448732,4.0,"Stem specific density (SSD, stem dry mass per ...",4,Wood density; stem specific density; wood spec...,Wood Dens g/cm3,0.588190515778088,g/cm3,Single,NaN,NaN,NaN,0.588191,g/cm3,NaN,NaN,0.892559,"Fyllas, N. M., S. Patino, T. R. Baker, G. Biel...",NaN,NaN,NaN

In [9]:
df_trait_id = df[["AccSpeciesName", "StdValue", "UnitName", "Reference"]]

In [13]:
df_trait_id_non_nan = df_trait_id[df_trait_id['StdValue'].notna()]

df_trait_id_non_nan.loc[:, "AccSpeciesName"] = (
    df_trait_id_non_nan["AccSpeciesName"].str.lower()
)

df_grouped = df_trait_id_non_nan.groupby("AccSpeciesName", as_index=False).agg(
    ssd_mean_g_cm3=("StdValue", "mean"),
    ssd_max_g_cm3=("StdValue", "max"),
    ssd_min_g_cm3=("StdValue", "min"),
    references=("Reference", lambda x: "; ".join(x.dropna().unique()))
)
df_grouped

,AccSpeciesName,ssd_mean_g_cm3,ssd_max_g_cm3,ssd_min_g_cm3,references
0,aegle marmelos,0.825728,0.880000,0.771456,"Chave, J., D. Coomes, S. Jansen, S. L. Lewis, ..."
1,aesculus hippocastanum,0.586531,1.040000,0.390000,"Kleyer, M., R. M. Bekker, I. C. Knevel, J. P. ..."
2,angophora floribunda,0.725120,0.757680,0.660000,"Chave, J., D. Coomes, S. Jansen, S. L. Lewis, ..."
3,aquilaria malaccensis,0.320000,0.320000,0.320000,"Chave, J., D. Coomes, S. Jansen, S. L. Lewis, ..."
4,aquilaria sinensis,0.366158,0.380000,0.344400,"Chave, J., D. Coomes, S. Jansen, S. L. Lewis, ..."
...,...,...,...,...,...
132,handroanthus impetiginosus,0.768140,0.990000,0.508000,"Chave, J., D. Coomes, S. Jansen, S. L. Lewis, ..."
133,heritiera fomes,0.816228,0.816228,0.816228,"Chave, J., D. Coomes, S. Jansen, S. L. Lewis, ..."
134,heritiera littoralis,0.825732,1.040000,0.680000,"Chave, J., D. Coomes, S. Jansen, S. L. Lewis, ..."
135,heteromeles arbutifolia,0.617722,0.630000,0.605733,"Preston, K. A., W. K. Cornwell, and J. L. DeNo..."
136,hevea brasiliensis,0.572970,0.950000,0.290000,"Fyllas, N. M., S. Patino, T. R. Baker, G. Biel..."

In [14]:
df_grouped.to_csv("ssd_cleaned.csv", index=False)